"""Repo hygiene guards (handoff E3).

Generated pipeline output and OS noise must never be tracked in git: logs
(``*.log``), yt-dlp partial-download stubs (``*.part``/``*.ytdl``), and Finder
metadata (``.DS_Store``). They bloat the clone and are regenerated by the
pipelines. Untracking is ``git rm --cached`` + ``.gitignore`` — never a history
rewrite. Mirrors the CI ``artifact-guard.yml`` job so the same violation fails
locally under pytest.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

# Pathspecs as used by the CI guard; each must match tracked files at any depth.
TRACKED_ARTIFACT_PATTERNS = [
    "*.log",
    "*.part",
    "*.ytdl",
    ".DS_Store",
]


def _tracked_files_matching(patterns: list[str]) -> list[str]:
    """Return tracked files matching any of the git pathspecs."""
    result = subprocess.run(
        ["git", "ls-files", "--", *patterns],
        capture_output=True,
        text=True,
        check=True,
        cwd=Path(__file__).resolve().parents[1],
    )
    return [line for line in result.stdout.splitlines() if line]


@pytest.mark.parametrize("pattern", TRACKED_ARTIFACT_PATTERNS)
def test_no_tracked_generated_artifacts(pattern: str) -> None:
    matches = _tracked_files_matching([pattern])
    assert matches == [], (
        f"Generated artifacts matching {pattern!r} are tracked in git; "
        f"untrack with 'git rm --cached' (history must not be rewritten): {matches}"
    )
