"""sitemap.xml and robots.txt emitters for the static journal site (M4).

Per ``docs/m4-site-spec.md`` (ActiveInferenceJournal): one ``<url>`` per INDEX
item plus the root, ``<lastmod>`` only when a real date is known (never
fabricated), no ``changefreq``/``priority``. ``robots.txt`` points crawlers at
the sitemap. Both files are generated by the builder, never committed by hand.
"""

from __future__ import annotations

from dataclasses import dataclass
from xml.sax.saxutils import escape

_SITEMAP_NS = "http://www.sitemaps.org/schemas/sitemap/0.9"


@dataclass(frozen=True)
class SitemapUrl:
    """One ``<url>`` entry: canonical ``loc`` and optional ISO-8601 ``lastmod``."""

    loc: str
    lastmod: str | None = None


def render_sitemap(urls: list[SitemapUrl]) -> str:
    """Render a sitemap urlset. ``lastmod`` is emitted only when present."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<urlset xmlns="{_SITEMAP_NS}">',
    ]
    for u in urls:
        lines.append("  <url>")
        lines.append(f"    <loc>{escape(u.loc)}</loc>")
        if u.lastmod:
            lines.append(f"    <lastmod>{escape(u.lastmod)}</lastmod>")
        lines.append("  </url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def render_robots(base_url: str) -> str:
    """robots.txt referencing the sitemap at ``base_url``."""
    return f"User-agent: *\nAllow: /\nSitemap: {base_url}sitemap.xml\n"
